name: "Structr start and deploy action"
description: "This action starts Structr and Neo4j and deploys a given webapp. The resulting stack can be used for testing or other CI purposes."

branding:
  icon: arrow-down-circle
  color: green

inputs:
  structr-version:
    description: "The version of Structr to start"
    required: true
    default: "4.2.0"
  neo4j-version:
    description: "The version of Neo4j to start"
    required: true
    default: "4.4"
  structr-webapp-path:
    description: "The path to the Structr webapp folder. Defaults to <github.workspace>/webapp"  
    required: true
    default: "${{ github.workspace }}/webapp"
  structr-license:
    description: "A valid Structr license key"
    required: false
    default: ""
  

runs:
  using: "composite"
  steps:
    - name: Print configuration
      run: echo "Running Structr:${{ inputs.structr-version }} with Neo4j:${{ inputs.neo4j-version }} \nDeploying from ${{ inputs.structr-webapp-path }}"
      shell: bash

    - name: Start Structr and Neo4j
      env:
          NEO4j_VERSION: ${{ inputs.neo4j-version }}
          STRUCTR_VERSION: ${{ inputs.structr-version }}
          STRUCTR_WEBAPP_PATH: ${{ inputs.structr-webapp-path }}
          STRUCTR_LICENSE: ${{ inputs.structr-license }}
      run: >-
        cd ${{ github.action_path }} && 
        sed -i "s|NEO4j_VERSION|$NEO4j_VERSION|g" docker-compose.yml &&
        sed -i "s|STRUCTR_LICENSE|$STRUCTR_LICENSE|g" docker-compose.yml &&
        sed -i "s|STRUCTR_VERSION|$STRUCTR_VERSION|g" docker-compose.yml &&
        sed -i "s|STRUCTR_WEBAPP_PATH|$STRUCTR_WEBAPP_PATH|g" docker-compose.yml &&
        docker-compose up -d
      shell: bash      

    - name: Deploy given webapp
      run: cd ${{ github.action_path }} && ./deploy.sh
      shell: bash