name: "Structr Deployment"
description: "Github action that start Structr and Neo4j and deploys a given webapp"
inputs:
  structr-version:
    description: "The version of Structr to start"
    required: true
    default: "4.2.0"
  neo4j-version:
    description: "The version of Neo4j to start"
    required: true
    default: "4.4"
  structr-webapp-path:
    description: "The path to the Structr webapp folder. Defaults to <github.workspace>/webapp"  
    required: true
    default: "${{ github.workspace }}/webapp"

runs:
  using: "composite"
  steps:
    - name: Print configuration
      run: echo "Running Structr:${{ inputs.structr-version }} with Neo4j:${{ inputs.neo4j-version }} \nDeploying from ${{ inputs.structr-webapp-path }}"
      shell: bash

    - name: Start Structr and Neo4j
      env:
          NEO4J_VERSION: ${{ inputs.neo4j-version }}
          STRUCTR_VERSION: ${{ inputs.structr-version }}
          STRUCTR_WEBAPP_PATH: ${{ inputs.structr-webapp-path }}
      run: >-
        sed -i "s|NEO4J_VERSION|$NEO4J_VERSION|g" "docker-compose.yml" &&
        sed -i "s|STRUCTR_VERSION|$STRUCTR_VERSION|g" "docker-compose.yml" &&
        sed -i "s|STRUCTR_WEBAPP_PATH|$STRUCTR_WEBAPP_PATH|g" "docker-compose.yml" &&
        docker-compose up -d
      shell: bash
      

    - name: Deploy given webapp
      run: ./deploy.sh
      shell: bash