on: [push]

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    name: Deploy and test
    steps:
      - uses: actions/checkout@v3
      - id: Test
        uses: structr/structr-deploy-action
        with:
          neo4j-version: '4.4'
          structr-version: '4.3-SNAPSHOT'
          structr-webapp-path: '${{ github.workspace }}/webapp'

      - name: "Run hello-world"
        run: curl -v localhost:8082/hello-world